apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elastic-credentials
  namespace: elk
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: elastic-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: elastic-password
      remoteRef:
        key: elasticsearch
        property: elastic-password
    - secretKey: kibana-password
      remoteRef:
        key: elasticsearch
        property: kibana-password
