global:
  enabled: true
server:
  dev:
    enabled: true
    devRootToken: root
  dataStorage:
    enabled: false
  service:
    enabled: true
    type: ClusterIP
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
injector:
  enabled: false
