apiVersion: v1
kind: Service
metadata:
  name: es-master-data
  namespace: elk
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: master-data
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: es-ingest
  namespace: elk
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: ingest
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
